### ISSUE TITLE
Search Crash

### ISSUE THREAD

**Issue by clmarshall** [veyesys/rapidvms#22]
![screenshot from 2015-06-16 11 39 50](https://cloud.githubusercontent.com/assets/3595063/8187165/6f83371e-141c-11e5-89cb-45ddcc5dab33.png)
**OS** = Ubuntu 15.04 x64
**OpenCVR** = 1.2.3

In local GUI - Click on SEARCH and then click on **Start** = CRASH

*Msg ID ======> uuid:{b6f16831-1d08-4402-b2bb-766f99bd623b 

Cannot mix incompatible Qt library (version 0x50400) with this library (version 0x50401)
./start.sh: line 4: 19320 Aborted                 (core dumped) ./bin/OpenCVR*

**---START EXTENDED COMMAND LOG ---**
*chad@Rufus:~/Downloads/OpenCVR-Ubuntu14.04-CentOS7-64bit-r1.2.3$ ./start.sh
Listening on 9000
Login with x/x, enable with 'x'
Sys path ve/
2015/06/16 11:34:13 AM [V]: Create the DB path ve/videodb/idb
2015/06/16 11:34:13 AM [V]: Create the DB file ve/videodb/idb/idb.vi
2015/06/16 11:34:13 AM [V]: No ref > 0
2015/06/16 11:34:13 AM [V]: InitRead StartTime 1434468717 EndTime 1434468721
2015/06/16 11:34:13 AM [V]: Update records ID 373 End
2015/06/16 11:34:13 AM [V]: No ref > 0
2015/06/16 11:34:13 AM [V]: HdfslibDelegate Connect HDFS  lib libhdfs.so !.
2015/06/16 11:34:13 AM [V]: HdfslibDelegate HDFS lib load error 
2015/06/16 11:34:13 AM [V]: Connecting HDFS lib load error 
2015/06/16 11:34:13 AM [V]: Init Init Device 1
2015/06/16 11:34:13 AM [V]: Init Id 1
2015/06/16 11:34:13 AM [V]: Init Init Device 2
2015/06/16 11:34:13 AM [V]: Init Id 2
Recv ======> <?xml version="1.0" encoding="UTF-8"?><SOAP-ENV:Envelope xmlns:SOAP-ENV="http://www.w3.org/2003/05/soap-envelope" xmlns:SOAP-ENC="http://www.w3.org/2003/05/soap-encoding" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsa5="http://www.w3.org/2005/08/addressing" xmlns:xmime="http://tempuri.org/xmime.xsd" xmlns:xop="http://www.w3.org/2004/08/xop/include" xmlns:ns1="http://docs.oasis-open.org/wsrf/bf-2" xmlns:tt="http://www.onvif.org/ver10/schema" xmlns:wsnt="http://docs.oasis-open.org/wsn/b-2" xmlns:wstop="http://docs.oasis-open.org/wsn/t-1" xmlns:tds="http://www.onvif.org/ver10/device/wsdl" xmlns:trt="http://www.onvif.org/ver10/media/wsdl" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:d="http://schemas.xmlsoap.org/ws/2005/04/discovery" >SOAP-ENV:Body<d:Hello>wsa:EndpointReferencewsa:Addressurn:OpenCVR/wsa:Address/wsa:EndpointReference<d:Types>tds:device/d:Types<d:Scopes MatchBy="onvif://www.onvif.org/location/country/china onvif://www.onvif.org/hardware/OpenCVR onvif://www.onvif.org/name/OpenCVR onvif://www.onvif.org/type/video_encoder ">/d:Scopes<d:XAddrs>http://0.0.0.0:27554966/d:XAddrs<d:MetadataVersion>22/d:MetadataVersion/d:Hello/SOAP-ENV:Body/SOAP-ENV:Envelope 

2015/06/16 11:34:13 AM [V]: HDD /dev/sda1 path /mnt/plex freeSize 1024274088
Msg ID ======>  

2015/06/16 11:34:13 AM [V]: VSCToolBar rect x:0 y:0 w:1920 h:1080 
2015/06/16 11:34:13 AM [V]: ClearVideoLayout Layout count before clearing it: 0
2015/06/16 11:34:13 AM [V]: ClearVideoLayout Layout count after clearing it: 0
2015/06/16 11:34:13 AM [V]: VSCPlayControl rect x:0 y:0 w:1920 h:1080 
WARNING: No module folder exists.
INFO: Module Loaded...QTSSFileModule [static]
INFO: Module Loaded...QTSSReflectorModule [static]
INFO: Module Loaded...QTSSRelayModule [static]
INFO: Module Loaded...QTSSAccessLogModule [static]
INFO: Module Loaded...QTSSFlowControlModule [static]
INFO: Module Loaded...QTSSPosixFileSysModule [static]
INFO: Module Loaded...QTSSAdminModule [static]
INFO: Module Loaded...QTSSMP3StreamingModule [static]
INFO: Module Loaded...QTSSAccessModule [static]
INFO: Module Loaded...QTSSVideoModule [static]
WARNING: No users file found at /etc/streaming/qtusers.
WARNING: No groups file found at /etc/streaming/qtgroups.
Streaming Server done starting up
2015/06/16 11:34:15 AM [V]: HDD /dev/sda1 path /mnt/plex freeSize 1024274088
2015/06/16 11:34:17 AM [V]: HDD /dev/sda1 path /mnt/plex freeSize 1024274088
File not found: .//mplugins/
2015/06/16 11:34:18 AM [V]: Plugin init error 
2015/06/16 11:34:18 AM [V]: MFramework runing
2015/06/16 11:34:18 AM [V]: UpdateUrl url rtsp://192.168.1.108:554
2015/06/16 11:34:18 AM [V]: UpdateUrl url rtsp://192.168.1.110:554
2015/06/16 11:34:18 AM [V]: CheckDevice url rtsp://192.168.1.108:554
2015/06/16 11:34:18 AM [V]: CheckDevice url rtsp://192.168.1.108:554
2015/06/16 11:34:18 AM [V]: StartRecord Start Record
2015/06/16 11:34:18 AM [V]: StartHdfsRecord Start Record
2015/06/16 11:34:18 AM [V]:  DeviceChangeCallbackFunc1 Device Change Callback 1 type 3
QObject::connect: Cannot queue arguments of type 'QVector<int>'
(Make sure 'QVector<int>' is registered using qRegisterMetaType().)
QObject::connect: Cannot queue arguments of type 'QVector<int>'
(Make sure 'QVector<int>' is registered using qRegisterMetaType().)
QObject::connect: Cannot queue arguments of type 'QVector<int>'
(Make sure 'QVector<int>' is registered using qRegisterMetaType().)
QObject::connect: Cannot queue arguments of type 'QVector<int>'
(Make sure 'QVector<int>' is registered using qRegisterMetaType().)
2015/06/16 11:34:18 AM [V]: VVIPCMgr Device Change Callback 1 type 3 begin
2015/06/16 11:34:18 AM [V]: VVIPCMgr Device Change Callback 1 type 3 begin
2015/06/16 11:34:18 AM [V]: Event Device Change Callback 1 type 3 Begin
2015/06/16 11:34:18 AM [V]: Event Device Change Callback 1 type 3 End 
2015/06/16 11:34:18 AM [V]: CheckDevice url rtsp://192.168.1.110:554
2015/06/16 11:34:18 AM [V]: CheckDevice url rtsp://192.168.1.110:554
2015/06/16 11:34:18 AM [V]: StartRecord Start Record
2015/06/16 11:34:18 AM [V]: StartHdfsRecord Start Record
2015/06/16 11:34:18 AM [V]:  DeviceChangeCallbackFunc1 Device Change Callback 2 type 3
2015/06/16 11:34:18 AM [V]: VVIPCMgr Device Change Callback 2 type 3 begin
2015/06/16 11:34:18 AM [V]: VVIPCMgr Device Change Callback 2 type 3 begin
2015/06/16 11:34:18 AM [V]: Event Device Change Callback 2 type 3 Begin
2015/06/16 11:34:18 AM [V]: Event Device Change Callback 2 type 3 End 
DEBUG: recv buffer size = 372480
2015/06/16 11:34:18 AM [V]: Create the DB path /mnt/plex
2015/06/16 11:34:18 AM [V]: Create the Block file /mnt/plex/videodb/mdb/0/a7a83bac-6d60-450d-b095-2df971f6c2e2.vm
2015/06/16 11:34:18 AM [V]: Add record ID 374
2015/06/16 11:34:19 AM [V]: MFramework runing
2015/06/16 11:34:19 AM [V]: HDD /dev/sda1 path /mnt/plex freeSize 1024273244
2015/06/16 11:34:20 AM [V]: MFramework runing
QObject::connect: Cannot queue arguments of type 'astring'
(Make sure 'astring' is registered using qRegisterMetaType().)
2015/06/16 11:34:21 AM [V]: MFramework runing
2015/06/16 11:34:21 AM [V]: HDD /dev/sda1 path /mnt/plex freeSize 1024271584
2015/06/16 11:34:22 AM [V]: MFramework runing
2015/06/16 11:34:23 AM [V]: MFramework runing
2015/06/16 11:34:23 AM [V]: HDD /dev/sda1 path /mnt/plex freeSize 1024270380
2015/06/16 11:34:24 AM [V]: MFramework runing
2015/06/16 11:34:25 AM [V]: MFramework runing
2015/06/16 11:34:25 AM [V]: HDD /dev/sda1 path /mnt/plex freeSize 1024268708
2015/06/16 11:34:26 AM [V]: MFramework runing
2015/06/16 11:34:27 AM [V]: MFramework runing
2015/06/16 11:34:27 AM [V]: HDD /dev/sda1 path /mnt/plex freeSize 1024267452
2015/06/16 11:34:28 AM [V]: MFramework runing
Recv ======> <?xml version="1.0" encoding="UTF-8"?>
<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:a="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:d="http://schemas.xmlsoap.org/ws/2005/04/discovery" xmlns:dn="http://www.onvif.org/ver10/network/wsdl">
 soap:Header
  <a:Action>http://schemas.xmlsoap.org/ws/2005/04/discovery/Probe/a:Action
  <a:MessageID>uuid:{30b950eb-7519-4b09-bb7d-7e534e767219}/a:MessageID
  <a:To>urn:schemas-xmlsoap-org:ws:2005:04:discovery/a:To
 /soap:Header
 soap:Body
  <d:Probe>
   <d:Types>dn:NetworkVideoTransmitter/d:Types
   <d:Scopes/>
  /d:Probe
 /soap:Body
/soap:Envelope

Msg ID ======> uuid:{30b950eb-7519-4b09-bb7d-7e534e767219 

Cannot mix incompatible Qt library (version 0x50400) with this library (version 0x50401)
./start.sh: line 4: 21705 Aborted                 (core dumped) ./bin/OpenCVR
chad@Rufus:~/Downloads/OpenCVR-Ubuntu14.04-CentOS7-64bit-r1.2.3$\*

**Comment by xsmart** [comment]
Cannot mix incompatible Qt library (version 0x50400) with this library (version 0x50401)
do you use the Qt 5.4.1? the OpenCVR is build with Qt 5.4.0.

**Comment by clmarshall** [comment]
5.4.0

**Comment by xsmart** [comment]
I think it is may be Ubuntu 15.10 use the Qt 5.4.1?

**Comment by angelscopilo** [comment]
same problem

**Comment by xsmart** [comment]
you can try the latest version https://github.com/veyesys/version
