### ISSUE TITLE
Failure at login

### ISSUE THREAD

**Issue by celem** [veyesys/rapidvms#29]
Login screen, then no matter what is entered in Password field, halts with this:

/home/ecomer/bin/opencvr/OpenCVR-Ubuntu14.04-CentOS7-64bit-r1.2.3/bin/OpenCVR: symbol lookup error: /home/ecomer/bin/opencvr/OpenCVR-Ubuntu14.04-CentOS7-64bit-r1.2.3/bin/OpenCVR: undefined symbol: _ZN7QString13toUtf8_helperERKS_

**Comment by xsmart** [comment]
we will create a ubuntu iso which has opencvr in later.

**Comment by celem** [comment]
When I lasted this it worked with Linux. So, it no longer works?

**Comment by xsmart** [comment]
we will add all Qt depended file next version

**Comment by clmarshall** [comment]
Rather than an ISO for Ubuntu we would prefer a DEB install package

**Comment by celem** [comment]
I certainly agree with clmarshall - "Rather than an ISO for Ubuntu we would prefer a DEB install package".

I assumed that "ISO" was just a typo.

**Comment by xsmart** [comment]
try the latest version .
