### ISSUE TITLE
Remaining linux build problems

### ISSUE THREAD

**Issue by Dehumanizer77** [veyesys/rapidvms#48]
Sorry for opening a new ticket again, in #47 I was instructed to use release 2.0.3, which I did and this time the compilation fails due to some missing libraries.
This is the end of compilation:

g++ -Wl,-rpath,/home/johny/Qt5.4.0/5.4/gcc_64 -Wl,-rpath,/home/johny/Qt5.4.0/5.4/gcc_64/lib -o OpenCVRClient debug/main.o debug/vscdashboard.o debug/vscdashboardtaskitem.o debug/vsclogin.o debug/vscmainwindows.o debug/vsctoobar.o debug/vscuserstatus.o debug/vscvidlist.o debug/vscvidlistframe.o debug/switchbutton.o debug/vscvidinf.o debug/vscviditeminf.o debug/vscvidtreeinf.o debug/vscviditemcam.o debug/vscviditememap.o debug/vscviditemvidstor.o debug/vscviditemview.o debug/vscvidtreecam.o debug/vscvidtreeemap.o debug/vscvidtreeview.o debug/vscvidlive.o debug/vscview.o debug/vscviewconf.o debug/vvidpbview.o debug/vidclientsetting.o debug/vscvidconfig.o debug/vscvidtreeconf.o debug/vscviditemaddcam.o debug/vscviditemaddstor.o debug/vscviditemcamconf.o debug/vscviditemclientconf.o debug/vscviditemdiskconf.o debug/vscviditememapconf.o debug/vscviditemstorconf.o debug/vscviditemviewconf.o debug/vidcamadd.o debug/vidcamsetting.o debug/vidstoradd.o debug/vidstorsetting.o debug/vscstorlicense.o debug/vscstoruser.o debug/vscstorversion.o debug/vschddedit.o debug/vschddoneedit.o debug/vsccaminfo.o debug/vsccamrec.o debug/vsclanguage.o debug/vsclicense.o debug/vscuser.o debug/vscversion.o debug/vidviewconf.o debug/videmapconf.o debug/vscvidsearchpb.o debug/qrc_vscmainwindows.o debug/moc_vscdashboard.o debug/moc_vscdashboardtaskitem.o debug/moc_vscvidlistframe.o debug/moc_vsclogin.o debug/moc_vscuserstatus.o debug/moc_vscvidlist.o debug/moc_vsctoolbar.o debug/moc_vscmainwindows.o debug/moc_vscvidtreeinf.o debug/moc_switchbutton.o debug/moc_vscvidinf.o debug/moc_vscvidtreeview.o debug/moc_vscvidtreeemap.o debug/moc_vscvidtreecam.o debug/moc_vscviewconf.o debug/moc_vscview.o debug/moc_vvidpbview.o debug/moc_vscvidlive.o debug/moc_vscvidtreeconf.o debug/moc_vidclientsetting.o debug/moc_vscvidconfig.o debug/moc_vidstoradd.o debug/moc_vidcamadd.o debug/moc_vidstorsetting.o debug/moc_vidcamsetting.o debug/moc_vscstorversion.o debug/moc_vscstorlicense.o debug/moc_vscstoruser.o debug/moc_vschddedit.o debug/moc_vschddoneedit.o debug/moc_vsccaminfo.o debug/moc_vsccamrec.o debug/moc_vscversion.o debug/moc_vsclanguage.o debug/moc_vsclicense.o debug/moc_vscuser.o debug/moc_vidviewconf.o debug/moc_videmapconf.o debug/moc_vscvidsearchpb.o debug/moc_oapis.o debug/moc_clientfactory.o debug/moc_storclient.o debug/moc_storfactory.o debug/moc_storstream.o debug/moc_storsyncinf.o   -L./../../3rdparty/leveldb/ -L./Debug -L./../../3rdparty/openssl-linux/ -L./../../3rdparty/onvifc/prj_linux/lib -L../../output/Debian-7.9-64bit/lib -L../../output/Debian-7.9-64bit/lib/x86_64-linux-gnu -lcmnlib -lavcodec -lavformat -lavutil -lswscale -lleveldb -lonvifc -lvelib -lveuilib -lPocoFoundation -lprotobuf -lssl -lcrypto -ldl -L/home/johny/Qt5.4.0/5.4/gcc_64/lib -lQt5PrintSupport -lQt5Widgets -lQt5Gui -lQt5Sql -lQt5XmlPatterns -lQt5Network -lQt5Xml -lQt5DBus -lQt5Concurrent -lQt5Core -lGL -lpthread 
/usr/bin/ld: error: cannot find -lcmnlib
/usr/bin/ld: error: cannot find -lleveldb
/usr/bin/ld: warning: skipping incompatible ./../../3rdparty/onvifc/prj_linux/lib/libonvifc.a while searching for onvifc
/usr/bin/ld: error: cannot find -lvelib
/usr/bin/ld: error: cannot find -lveuilib
/usr/bin/ld: error: cannot find -lPocoFoundation
/usr/bin/ld: error: cannot find -lprotobuf
/usr/bin/ld: error: cannot find -lonvifc

and after that, a myriad of undefined references (I assume due to these missing libraries), resulting in: 
collect2: error: ld returned 1 exit status
make[2]: **\* [OpenCVRClient] Error 1
make[2]: Leaving directory `/usr/src/opencvr-r2.0.3/client/prj_linux'
make[1]: *** [vepro_build] Error 2
make[1]: Leaving directory`/usr/src/opencvr-r2.0.3/client'
make: **\* [all] Error 2

What should I do to be able to finally compile the source sucessfully?

**Comment by xsmart** [comment]
You need in the top dir make

**Comment by xsmart** [comment]
Your Skype?

**Comment by xsmart** [comment]
And remove the installation of qt.2.0.3 will build qt from source

**Comment by Dehumanizer77** [comment]
Ok, I have used the current Qt as with previous versions, so maybe that was the problem, I will try again.

**Comment by Dehumanizer77** [comment]
Another problem, onvifc won't build...

cd onvifc/prj_linux/ ; qmake .;
Project MESSAGE: You are running qmake on a generated .pro file. This may not work!
Project WARNING: CONFIG+=help is deprecated. Use QT+=help instead.
Project ERROR: Unknown module(s) in QT: help-private
make: *** [onvifc_build] Error 3

What now?

**Comment by xsmart** [comment]
You can remove the help module in the Onvifc.pro

**Comment by Dehumanizer77** [comment]
Still no success. 3rd party stuff has compiled succesfully, including Qt, but there are still missing libraries.

/usr/bin/ld: error: cannot find -lcmnlib
/usr/bin/ld: error: cannot find -lvelib
/usr/bin/ld: error: cannot find -lveuilib
/usr/bin/ld: error: cannot find -lprotobuf

**Comment by xsmart** [comment]
current the build support on the Ubuntu 14.04, which linux you use ?

**Comment by Dehumanizer77** [comment]
If I had Ubuntu 14.04,  I wouldn't have to compile it from source, I would used the precompiled package.
I am trying to compile it on Debian Wheezy

**Comment by xsmart** [comment]
the precompiled can be used in the Centos 7, maybe it can run Debian Wheezy?

**Comment by Dehumanizer77** [comment]
That's the first thing I have tried, it doesn't work, glibc version is conflicting.

**Comment by xsmart** [comment]
rapidvms do not support build from source for linux, you can try windows or use the prebuild version.

**Comment by xsmart** [comment]
full source code will ready soon.
