### ISSUE TITLE
Undefined reference error 

### ISSUE THREAD

**Issue by shoknshok** [veyesys/rapidvms#54]
I'm attempting to build r.2.0.3 version but meeting this error:

`.obj/qatomicvalue.o: In function`QPatternist::AbstractFloat<false>::stringValue() const':
qatomicvalue.cpp:(.text._ZNK11QPatternist13AbstractFloatILb0EE11stringValueEv[_ZNK11QPatternist13AbstractFloatILb0EE11stringValueEv]+0x148): undefined reference to `qdtoa(double, int, int, int*, int*, char**, char**)'
.obj/qatomicvalue.o: Inqtbase-opensource-src-5.5.1/tests/benchmarks/gui/graphicsview/qgraphicsview/qgraphicsview.pro
 function`QPatternist::AbstractFloat<true>::stringValue() constqtbase-opensource-src-5.5.1/tests/benchmarks/gui/graphicsview/qgraphicslayout/
':
qatomicvalue.cpp:(.text._ZNK11QPatternist13AbstractFloatILb1EE11stringValueEv[_ZNK11QPatternist13AbstractFloatILb1EE11stringValueEv]+0x148)yes
checking for C compiler default output file name... a.out
qtbase-opensource-src-5.5.1/tests/benchmarks/gui/graphicsview/qgraphicslayout/tst_qgraphicslayout.cpp
qtbase-opensource-src-5.5.1/tests/benchmarks/gui/graphicsview/qgraphicslayout/qgraphicslayout.pro
qtbase-opensource-src-5.5.1/tests/benchmarks/gui/graphicsview/qgraphicsanchorlayout/
qtbase-opensource-src-5.5.1/tests/benchmarks/gui/graphicsview/qgraphicsanchorlayout/tst_qgraphicsanchorlayout.cpp
qtbase-opensource-src-5.5.1/tests/benchmarks/gui/graphicsview/qgraphicsanchorlayout/qgraphicsanchorlayout.pro
qtbase-opensource-src-5.5.1/tests/benchmarks/gui/graphicsview/functional/
:qtbase-opensource-src-5.5.1/tests/benchmarks/gui/graphicsview/functional/functional.pro
 undefined reference to `qdtoa(double, intqtbase-opensource-src-5.5.1/tests/benchmarks/gui/graphicsview/functional/GraphicsViewBenchmark/
, int,qtbase-opensource-src-5.5.1/tests/benchmarks/gui/graphicsview/functional/GraphicsViewBenchmark/widgets/
 int*, qtbase-opensource-src-5.5.1/tests/benchmarks/gui/graphicsview/functional/GraphicsViewBenchmark/widgets/abstractitemcontainer.cpp
int*, char**, char**)'
.obj/qdecimal.o: In function`QPatternist::Decimal::toString(double)':
qdecimal.cpp:(.text+0x503): undefined reference to `qdtoa(double, int, int, int*, int*, char**, char**)'
collect2: error: ld returned 1 exit status
qtbase-opensource-src-5.5.1/tests/benchmarks/gui/graphicsview/functional/GraphicsViewBenchmark/widgets/simplelist.h
qtbase-opensource-src-5.5.1/tests/benchmarks/gui/graphicsview/functional/GraphicsViewBenchmark/widgets/webview_p.h
qtbase-opensource-src-5.5.1/tests/benchmarks/gui/graphicsview/functional/GraphicsViewBenchmark/widgets/itemrecyclinglistview.h
qtbase-opensource-src-5.5.1/tests/benchmarks/gui/graphicsview/functional/GraphicsViewBenchmark/widgets/scroller_p.h
qtbase-opensource-src-5.5.1/tests/benchmarks/gui/graphicsview/functional/GraphicsViewBenchmark/widgets/menu.h
qtbase-opensource-src-5.5.1/tests/benchmarks/gui/graphicsview/functional/GraphicsViewBenchmark/widgets/itemrecyclinglist.cpp
qtbase-opensource-src-5.5.1/tests/benchmarks/gui/graphicsview/functional/GraphicsViewBenchmark/widgets/dummydatagen.h
qtbase-opensource-src-5.5.1/tests/benchmarks/gui/graphicsview/functional/GraphicsViewBenchmark/widgets/dummydatagen.cpp
qtbase-opensource-src-5.5.1/tests/benchmarks/gui/graphicsview/functional/GraphicsViewBenchmark/widgets/listitemcontainer.cpp
qtbase-opensource-src-5.5.1/tests/benchmarks/gui/graphicsview/functional/GraphicsViewBenchmark/widgets/recycledlistitem.cpp
qtbase-opensource-src-5.5.1/tests/benchmarks/gui/graphicsview/functional/GraphicsViewBenchmark/widgets/commandline.h
make[4]: *** [../../lib/libQt5XmlPatterns.so.5.5.1] Error 1`

As I know, the qdtoa() function is not defined that cause this error but I don't know how to fix this. Please help me to fix this!

Thanks for advance

**Comment by xsmart** [comment]
you build for linux version?

**Comment by shoknshok** [comment]
Thanks for repliment, I'm building for linux and using ubuntu14.04.1 to
build it. If you wonder any infomation. Please let me know!

**Comment by shoknshok** [comment]
I retry to build the source from main branch, after fix some dependencies the final error still the same ass above as I mentioned. By the way, which IDE should I use to develop this source?

**Comment by xsmart** [comment]
you can use the prebuild version or build from source for windows.

**Comment by xsmart** [comment]
full source code will ready soon.
