### ISSUE TITLE
convert raw data to cv::Mat

### ISSUE THREAD

**Issue by ahmadi219** [veyesys/rapidvms#64]
Hi 
I want to display current frame that is sending to client (in server) .
Which parameter I use to convert it to cv::Mat ?
I added these codes in **OAPIServer::DataHandler1** method, but it displayed no thing.

cv::Mat my_mat(100, 100, CV_8UC3 , frame.dataBuf);
    cv::imshow("current frame ", my_mat);
    cvWaitKey(10);

What Should I do to convert raw data of camera frame to cv::Mat ? 
and where the raw data of frame is stored ? Is it in VideoFrame or pRecv in this blow code?
s32 nRetBody = m_pSocket->Recv((void _)__pRecv_*, len);

Best Regards

**Comment by xsmart** [comment]
The DataHandler1 is for the encoded frame, you need decode the data

**Comment by ahmadi219** [comment]
Hi 
thanks for your attention 
When I decode frame with VPlay::PutRawdata, how I can get decoded data ?
Best Regards

**Comment by xsmart** [comment]
all the source code is open, you can get the rawdata
