### ISSUE TITLE
Build on Ubuntu 14.04 libcmnlib.so undefined reference

### ISSUE THREAD

**Issue by doanthaibao** [veyesys/rapidvms#66]
Hi guys,
I tried to build release 2.0.7 and master code and faced same issue with libcmnlib.so (maybe don't have lastest version). I build successfully with version 2.0.3
![untitled](https://cloud.githubusercontent.com/assets/9799644/19469087/fa2d0828-9543-11e6-98cc-fe10499d39be.png)

Please help me check it.
Regards,
Bao

**Comment by xsmart** [comment]
Rapidvms only support windows build from git, for other platform you can use the pre-build version
