### ISSUE TITLE
SOURCE CODE MISSING for veuilib(libveuilib.so), velib(libvelib.so), xcmnlib(libcmnlib.so)

### ISSUE THREAD

**Issue by RaghavaKondiparthi** [veyesys/rapidvms#67]
Hi,

When I am trying to build the project it is showing lot of build errors. I found there is source code missing for veuilib(libveuilib.so), velib(libvelib.so), xcmnlib(libcmnlib.so). 
Are you doing it intentionally or by mistake.
I don't understand why you are posting on git if you are not intended to provide the full source code.

Regards,
Raghava Kondiparthi

**Comment by xsmart** [comment]
all the source code is open.
