### ISSUE TITLE
SOURCE CODE MISSING for veuilib(libveuilib.so), velib(libvelib.so), xcmnlib(libcmnlib.so). SEEMS IT IS INTENTIONAL

### ISSUE THREAD

**Issue by RaghavaKondiparthi** [veyesys/rapidvms#68]
Hi,

When I am trying to build the project it is showing lot of build errors. I found there is source code missing for veuilib(libveuilib.so), velib(libvelib.so), xcmnlib(libcmnlib.so).
Are you doing it intentionally or by mistake.
I don't understand why you are posting on git if you are not intended to provide the full source code.

Regards,
Raghava Kondiparthi

**Comment by xsmart** [comment]
yes the veuilib(libveuilib.so), velib(libvelib.so), xcmnlib(libcmnlib.so) source code is not open now.

**Comment by RaghavaKondiparthi** [comment]
HI,
I am working on implementing the the onvif functionality in iotivity. which is again a opensource. In the process I require a working model for onvif. Please let me know what is the best way of getting the source code for the above libraries. If it is paid service please let me know the price.

Thanks and Regards,
Raghava Kondiaprthi

**Comment by xsmart** [comment]
For onvif function, you can refer the onvifcpplib project.

**Comment by xsmart** [comment]
All the source code will be open soon.
