### ISSUE TITLE
I want to build the rapid_vms sources for raspberry pi3.

### ISSUE THREAD

**Issue by kgss** [veyesys/rapidvms#77]
I am seeing the file of rules-pi3.mk.
How can I install gcc-raspberry-x64?
I want to build the rapid_vms sources for raspberry pi3.
Could you explain the details?

**Comment by xsmart** [comment]
the gcc for raspbeery cross compile can be download here https://github.com/raspberrypi/tools/tree/master/arm-bcm2708/arm-rpi-4.9.3-linux-gnueabihf
