### ISSUE TITLE
Cannot build Linux 64-bit version

### ISSUE THREAD

**Issue by ChrisBlood** [veyesys/rapidvms#78]
Tested with master and release 3.5 Ubuntu 16.04

Quite a few errors but the missing cmnlib seems critical. I followed the instructions on the gihub page and installed the required packages, updated VE_PATH and ran make.

/usr/bin/ld: cannot find -lcmnlib
collect2: error: ld returned 1 exit status
Makefile:132: recipe for target 'libvelib.so' failed

/usr/bin/ld: cannot find -lcmnlib
/usr/bin/ld: cannot find -lvelib
collect2: error: ld returned 1 exit status
Makefile:344: recipe for target 'libveuilib.so' failed

**Comment by xsmart** [comment]
sorry, the 3.5 only can build for windows by vs2013, we will add build for linux & Mac soon

**Comment by ChrisBlood** [comment]
Does 3.2 build for Linux? Thank you

**Comment by xsmart** [comment]
i will check with our team.

**Comment by xsmart** [comment]
https://github.com/veyesys/rapidvms/releases/tag/r4.1 can be build for linux
