### ISSUE TITLE
Live view is not displayed.

### ISSUE THREAD

**Issue by chomooho** [veyesys/rapidvms#82]
In rapidvms-r2.0.7, /192.168.1.97:80/onvif/device_service is connected and live view is displayed.
![27](https://user-images.githubusercontent.com/31305708/29850151-7e948bca-8d66-11e7-8a99-5ab6cd05f13e.jpg)
The followings are captured packets by Wireshark in rapidvms- r2.0.7.
[live0830r207.zip](https://github.com/veyesys/rapidvms/files/1262098/live0830r207.zip)

In rapidvms-r4.2, /192.168.1.97:80/onvif/device_service is connected and the camera status is changed to green color.
![42](https://user-images.githubusercontent.com/31305708/29850193-c8c65fde-8d66-11e7-977a-ebec570b485a.jpg)
But live view is not displayed, and in console messages “Stor Server Config is not init” is printed when RapidClient is run.
The followings are captured packets by Wireshark in rapidvms-r4.2.
[live0830r42.zip](https://github.com/veyesys/rapidvms/files/1262102/live0830r42.zip)
Please solve the problems.

**Comment by xsmart** [comment]
live0830r207.zip use MJPEG in RTSP, but the live0830r42.zip use H264 in RTSP, could you check the stream 1 & stream 2 in the Camera setting page?

**Comment by chomooho** [comment]
When I check the stream 1 & stream 2 in the Camera setting, 'Auto' is off
 and streams are set to H.264 with shadowing.
I turn 'Auto' on, and set stream 1 and stream 2 to H.264, and press 'Apply' button.
Then Live view is displayed.
Thank you xsmart.
